export enum SidebarLayoutEvent {
  AnchorMouseOver = 'sidebar-layout.anchormouseover',
  AnchorMouseLeave = 'sidebar-layout.anchormouseleave',
  AnchorClick = 'sidebar-layout.anchorclick',
  AnnotationUpdateNotebook = 'sidebar-layout.annotationupdatenb',
  ClickLogo = 'sidebar-layout.clicklogo',
  ClickLogout = 'sidebar-layout.clicklogout',
  ClickNotebookPanel = 'sidebar-layout.notebookpanel',
  ClickUsername = 'sidebar-layout.clickusername',
  Close = 'sidebar-layout.sidebarclose',
  Destroy = 'sidebar-layout.destroy',
  Init = 'sidebar-layout.init',
  NotebookPanelNewNotebookCreated = 'sidebar-layout.notebookpanelcreated',
  NotebookSharingModeUpdated = 'sidebar-layout.notebookmodeupdated',
  RequestLogin = 'sidebar-layout.requestlogin',
}
