export enum AppEvent {
  AnchorClick = 'app.anchorclick',
  AnchorMouseOver = 'app.anchormouseover',
  AnchorMouseLeave = 'app.anchormouseleave',
  AnnotationCreateSuccess = 'app.annotationcreatesuccess',
  AnnotationDeleteSuccess = 'app.annotationdeletesuccess',
  AnnotationDeleteClick = 'app.annotationdeleteclick',
  AnnotationEditComment = 'app.annotationeditcomment',
  AnnotationMouseEnter = 'app.annotationmouseenter',
  AnnotationMouseLeave = 'app.annotationmouseleave',
  AnnotationUpdateNotebook = 'app.annotationupdatenotebook',
  Clear = 'app.clear',
  CommentUpdate = 'app.commentupdate',
  KeyUpEscape = 'app.keyupescape',
  Logout = 'app.logout',
  NotebookCreateSuccess = 'app.notebookcreatesuccess',
  SearchResponse = 'app.searchresponse',
  SidebarCollapse = 'app.sidebarcollapse',
}
